apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: game-controller
  template:
    metadata:
      labels:
        component: game-controller
    spec:
      containers:
        - name: game-contoller
          image: aaronv70/c-server
          ports:
            - containerPort: 20001

---

apiVersion: v1
kind: Service
metadata:
  name: server-svc
spec:
  type: ClusterIP
  selector: 
    component: game-controller
  ports:
    - name: http
      port: 20001
      targetPort: 20001
      protocol: UDP
  
