FROM python:3-alpine

WORKDIR /api

RUN python3 -m venv venv

RUN . venv/bin/activate

COPY ./requirements.txt ./requirements.txt

RUN pip install --no-cache -r requirements.txt 

COPY . .

CMD ["flask","run","--host=0.0.0.0"]
